//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZTB.OA.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class R_UserInfo_ActionInfo
    {
        public int Id { get; set; }
        public string HasPermission { get; set; }
        public Nullable<int> UserInfoId { get; set; }
        public Nullable<int> ActionInfoId { get; set; }
        public string DelFag { get; set; }
        public int ActionInfo_Id { get; set; }
        public int UserInfoId1 { get; set; }
        public int ActionInfoId1 { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
        public virtual ActionInfo ActionInfo { get; set; }
    }
}
