//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZTB.OA.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class WF_Instance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WF_Instance()
        {
            this.FileInfo = new HashSet<FileInfo>();
            this.WF_Step = new HashSet<WF_Step>();
        }
    
        public int Id { get; set; }
        public string InstanceName { get; set; }
        public int StartBy { get; set; }
        public System.DateTime StartTime { get; set; }
        public short Level { get; set; }
        public string Content { get; set; }
        public string Remark { get; set; }
        public string DelFag { get; set; }
        public Nullable<System.Guid> WF_InstanceId { get; set; }
        public int WP_TempId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileInfo> FileInfo { get; set; }
        public virtual WP_Temp WP_Temp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WF_Step> WF_Step { get; set; }
    }
}
