//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     如需对单个文件扩展请使用部分类，否则当文本模板文件再次保存时将把修改冲刷掉
// </auto-generated>
//------------------------------------------------------------------------------
using System.Text;
using System.Threading.Tasks;
using ZTB.OA.DALFactory;
using ZTB.OA.EFDAL;
using ZTB.OA.IBLL;
using ZTB.OA.IDAL;
using ZTB.OA.Model;

namespace ZTB.OA.BLL
{	
	public partial  class UserInfoService: BaseService<UserInfo>, IUserInfoService
    {
     
    }
}
